use_frameworks!

platform :ios, '13.0'

#plugin 'cocoapods-art', :sources => [
#'ios'
#]

target 'KetchSDK_Example' do
  pod 'KetchSDK/CCPA', :path => '../'
  pod 'KetchSDK/TCF', :path => '../'
  pod 'KetchSDK/UI', :path => '../'

  target 'KetchSDK_Tests' do
    inherit! :search_paths

  end
end
