use_frameworks!

platform :ios, '15.0'

#plugin 'cocoapods-art', :sources => [
#'ios'
#]

target 'KetchSDK_Example' do
#  pod 'KetchSDK/UI', :path => '../'

  pod 'KetchSDK/UI',
  :git => 'git@github.com:ketch-com/ketch-ios.git',
  :branch => 'version_3'

  target 'KetchSDK_Tests' do
    inherit! :search_paths

  end
end
