use_frameworks!

platform :ios, '13.0'

#plugin 'cocoapods-art', :sources => [
#'ios'
#]

target 'KetchSDK_Example' do
  pod 'KetchSDK', :path => '../'
#  pod 'consentmanager'
#  pod 'UsercentricsUI', '2.7.4'
#  pod 'KetchSDK'
#  pod 'Alamofire'

  target 'KetchSDK_Tests' do
    inherit! :search_paths

  end
end
