name: iOS CI

on:
  push:
    branches:
    - main
    - lib
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_USERNAME: "alyfar@transcenda.com"
      # ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_PASSWORD: "APB16yVc17JFdU4SR4uiZnWb3Hs"
      
    steps:
    - uses: actions/checkout@v3

    - name: Step 1 - Create a temporary artifact folder ketchSDK
      run: mkdir ketchSDK

    - name: Step 2 - Add artifacts to publish to the temp folder
      run: |
        cp -a Sources ketchSDK/
        cp -a KetchSDK.podspec ketchSDK/
        cp -a LICENSE ketchSDK/

    - name: Step 3 - Archive using zip or tar
      uses: NSCoder/archive-action@v1.0.0
      with:
        args: tar -czvf ketchSDK.tar.gz ketchSDK/

    - name: Step 4 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: ketchSDK
        path: ketchSDK.tar.gz
        
    - name: Step 5 - Upload Artifact to jfrog.io/artifactory
      run: |
        curl -u"${{ env.ARTIFACTORY_USERNAME }}":"${{ env.ARTIFACTORY_PASSWORD }}" -XPUT https://ketch.jfrog.io/artifactory/ios/KetchSDK/ -T ketchSDK.tar.gz

      
